### ISSUE TITLE
Logging: Framecount, EyeOpen, EyeClose, 

### ISSUE THREAD

**Issue by bastianilso** [med-material/bci-kiwi-runner-redux#4]
- we should log the current “Framecount” from Unity (Time.frameCount). This allows us to check whether there is “game lag” by comparing Timestamps to number of frames passed.
- BlinkLog only has the value “Blink”, it would be better if we implement it as “EyeOpen” and “EyeClose”. I will do this in handstrengthener too, so if you want, you can wait until I have updated the implementation there.

**Comment by ingebronx** [comment]
Updated with the newest version of the LoggingManager.
